import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CardTendenciaYoutube from "../components/CardTendenciaYoutube";
const Home = ({ results }) => {
  console.log(results);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          {results &&
            results.slice(0).map((video, videoid) => {
              return <CardTendenciaYoutube video={video} key={videoid} />;
            })}
        </div>
      </main>
    </div>
  );
};
export default Home;

export async function getServerSideProps() {
  try {
    const MY_PLAYLIST = process.env.YOUTUBE_PLAYLIST_ID;
    const API_KEY = process.env.YOUTUBE_API_KEY;
    const REQUEST_URL = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=${MY_PLAYLIST}&key=${API_KEY}&maxResults=6`;
    const response = await fetch(REQUEST_URL);
    const results = await response.json();
    // console.log(results);

    // const MY_PLAYLIST_ESTRENO = process.env.YOUTUBE_PLAYLIST_ID_ESTRENO;
    // const API_KEY_ESTRENO = process.env.YOUTUBE_API_KEY;
    // const REQUEST_URL_ESTRENO = `https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=${MY_PLAYLIST_ESTRENO}&key=${API_KEY_ESTRENO}&maxResults=50`;
    // const responseEstreno = await fetch(REQUEST_URL_ESTRENO);
    // const resultsEstreno = await responseEstreno.json();
    // console.log(resultsEstreno);

    return {
      props: {
        results: results.items,
      },
    };
  } catch (error) {
    // console.log(error);
    return { props: { success: false, error: "Error!" } };
  }
}
